name: GeometryDash
version: '${project.version}'
main: com.githubaziaristocat.geometrydash.GeometryDash
api-version: 1.17
authors: [ AziAristocat ]
description: GeometryDash in Minecraft!!!!!
website: https://github.com/AziAristocat
commands:
  geodplay:
    description: Put your item in the main hand to the head.
    aliases: []
    permission: geometrydash.command.geodplay
    permission-message: You do not have permission to perform this command.
    usage: /geodplay

permissions:
  geometrydash.command.*:
    description: Allows you to perform commands in this plugin.
    children:
      geometrydash.command.geodplay: true
  geometrydash.command.geodplay:
    description: Allows you to perform /playgeod command.
    default: true